### ISSUE TITLE
Can't Craft some items when the beta version is present FABRIC 1.21.5

### ISSUE THREAD

**Issue by Nebula434** [DashieDev/DoggyTalentsNext#141]
this mod is causing users to not be able to craft pickaxes, for some reason the top right square in the 3x3 crafting grid is entirely unusable. screenshot for proof. 
Logs say this

[04:03:29] [Server thread/ERROR]: Failed to handle packet class_2813[containerId=6, stateId=18, slotNum=0, buttonNum=0, clickType=PICKUP, changedSlots={0=><empty>, 1=><empty>, 3=><empty>, 2=><empty>, 7=><empty>, 6=><empty>, 4=><empty>, 8=><empty>, 9=><empty>}, carriedItem=class_10939[item=Reference{ResourceKey[minecraft:item / minecraft:furnace]=minecraft:furnace}, count=1, components=class_10936[addedComponents={}, removedComponents=[]]]], suppressing error
net.minecraft.class_148: Container click
	at knot/net.minecraft.class_1703.method_7593(class_1703.java:352) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_12076(class_3244.java:1927) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2813.method_12191(class_2813.java:54) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2813.method_65081(class_2813.java:14) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:882) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:178) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:858) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:826) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:712) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:290) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException: Ingredient can't contain air
	at knot/net.minecraft.class_1856.method_61674(class_1856.java:47) ~[server-intermediary.jar:?]
	at knot/com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109) ~[datafixerupper-8.0.16.jar:?]
	at knot/net.minecraft.class_1856.<init>(class_1856.java:41) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1856.method_8101(class_1856.java:88) ~[server-intermediary.jar:?]
	at knot/doggytalents.api.impl.CasingMaterial.getIngredient(CasingMaterial.java:69) ~[DoggyTalentsNext%5BFabric%5D-1.21.5-1.18.46-beta.jar:?]
	at knot/doggytalents.common.util.DogBedUtil.getCasingFromStack(DogBedUtil.java:69) ~[DoggyTalentsNext%5BFabric%5D-1.21.5-1.18.46-beta.jar:?]
	at knot/doggytalents.common.inventory.recipe.DogBedRecipe.matches(DogBedRecipe.java:51) ~[DoggyTalentsNext%5BFabric%5D-1.21.5-1.18.46-beta.jar:?]
	at knot/doggytalents.common.inventory.recipe.DogBedRecipe.method_8115(DogBedRecipe.java:20) ~[DoggyTalentsNext%5BFabric%5D-1.21.5-1.18.46-beta.jar:?]
	at knot/net.minecraft.class_10289.method_64697(class_10289.java:56) ~[server-intermediary.jar:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at knot/net.minecraft.class_1863.method_8132(class_1863.java:152) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1734.mixinextras$bridge$method_8132$21(class_1734.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1734.wrapOperation$dfj000$owo$captureRecipeEntry(class_1734.java:2055) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1734.method_64650(class_1734.java:70) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1734.method_7667(class_1734.java:89) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1703.method_34249(class_1703.java:469) ~[server-intermediary.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at knot/net.minecraft.class_1703.method_30010(class_1703.java:467) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1703.method_7593(class_1703.java:342) ~[server-intermediary.jar:?]
	... 17 more

![Image](https://github.com/user-attachments/assets/cef128ea-0414-4552-8081-fa38b9b2dbec)

[latest.log](https://github.com/user-attachments/files/20153922/latest.log)

attached crash log as well, apologies for STDOUT being spammed idk how to deal with it?

**Comment by DashieDev** [comment]
Are you sure that it is DTN's fault since i just tested it on a fabric instance and the recipe still works fine. Beside as far as i am awared, DTN recipe doesn't do anything to block other recipe from being crafted.....

**Comment by Nebula434** [comment]
> Are you sure that it is DTN's fault since i just tested it on a fabric instance and the recipe still works fine. Beside as far as i am awared, DTN recipe doesn't do anything to block other recipe from being crafted.....

So far yes, i've gone thru my mod list and the problem goes away once DoggyTalentsNext[Fabric]-1.21.5-1.18.46-beta.jar is removed from the server mod list. It works perfectly fine in singeplayer, however multiplayer it doesnt let me use the top right out of the crafting grid, sometimes even the bottom right. Even did a re-download of the file, hope ur having a great day

**Comment by DashieDev** [comment]
Weird for some reason i just tested on a server instance and i can still use the crafting table normally.

**Comment by DashieDev** [comment]
Upon investigating your log it might really is DTN's fault. I am investigating this.

**Comment by Nebula434** [comment]
> Upon investigating your log it might really is DTN's fault. I am investigating this.

Awesome! ETA u think on a patch for it? my friends and I really love this mod, really appreciate all the work you've done on it!

**Comment by DashieDev** [comment]
I am not sure since i still have a bit of things to fix on the update but it will be ready shortly.

**Comment by DashieDev** [comment]
Patch coming today!

**Comment by Nebula434** [comment]
> Patch coming today!

Hope i didnt come off as rushing, just was curious. Thanks for being so quick with this, ur the best!!

**Comment by DashieDev** [comment]
Dang bad news. I am sorry to say this but i might need a bit more time since I am not feeling very well currently.....

**Comment by Nebula434** [comment]
> Dang bad news. I am sorry to say this but i might need a bit more time since I am not feeling very well currently.....

Feel better! take ur rest, drink some water and get that vitamin c in you! much love

**Comment by DashieDev** [comment]
DTN ```1.18.51``` is finalized, 1.21.5 fabric build will be ready soon! Really sorry for the wait.

**Comment by Nebula434** [comment]
> DTN `1.18.51` is finalized, 1.21.5 fabric build will be ready soon! Really sorry for the wait.

Thank you for the update, i hope you're feeling better, seriously love this mod thank u for keeping up the hard work!!!

**Comment by DashieDev** [comment]
```1.18.51``` is released for Fabric 1.21.5, i hope the bug is fixed on your side with this build.

**Comment by Nebula434** [comment]
> `1.18.51` is released for Fabric 1.21.5, i hope the bug is fixed on your side with this build.

Still getting hit with the same error sadly, do u have any known incompatibilities with ur mod? i couldn't imagine it conflicts with anything really. 

[latest.log](https://github.com/user-attachments/files/20302499/latest.log)

**Comment by DashieDev** [comment]
What? Yeah ....... It might be a conflict going on ..... Could you help me pinpoint which mod that cause the problem on your side?

**Comment by DashieDev** [comment]
Oh nvm. I think i am going to send you a test build before i upload it just to make sure eveything goes well ........

**Comment by DashieDev** [comment]
https://drive.google.com/file/d/1MxY3DZ6wqwdnqs-89G8ZN0kLpQ9wCMnu/view?usp=sharing
Could you try this build ?

**Comment by Nebula434** [comment]
> https://drive.google.com/file/d/1MxY3DZ6wqwdnqs-89G8ZN0kLpQ9wCMnu/view?usp=sharing Could you try this build ?

problem fixed! you are the best!

**Comment by DashieDev** [comment]
Fixed in DTN ```1.18.53```, Fabric 1.21.5 will be ported soon.
