### ISSUE TITLE
icon overlapping when opening attributes tab

### ISSUE THREAD

**Issue by VaporeonScripts** [DashieDev/DoggyTalentsNext#157]
normally:

<img width="801" height="598" alt="Image" src="https://github.com/user-attachments/assets/7fd62704-4345-48ec-9237-5a2cc7b02bbf" />
issue:

<img width="1032" height="633" alt="Image" src="https://github.com/user-attachments/assets/9299a618-583d-4778-830f-246403aee7db" />

**Comment by DashieDev** [comment]
You can customize the button offset or disable it in the client config.

**Comment by VaporeonScripts** [comment]
yeah but it cant be fixed with that... since its the same x and y but the inventory is moved on the right when that page is opened... u should make it so that it calculates the distance and adjusts it properly..

**Comment by DashieDev** [comment]
Currently It does adjust properly within the vanilla context. That window is another mod's and is out of my control. I will still see what I can do. In the meantime you can disable the button.
