### ISSUE TITLE
Does armor works correct on Fabric version?

### ISSUE THREAD

**Issue by Kavaltheone** [DashieDev/DoggyTalentsNext#67]
Hello.
On old wiki talent Doggy Armor shows how Netherite armor fills whole armor indicators. On version 1.18.8 for Fabric it seems that armor values don't apply correctly. When first open Armor Inventory it shows no icons. When put on any armor piece it applies it's armor value and stops. You can take off armor or add other pieces - armor icons stays the same. And armor value stays the same as hitting dog with sword in any armor set (tried Leather, Iron, Gold, Diamond and Netherite) makes about same damage, but it's less then was first when dog was without armor.
On screens I first put Iron chest and it gave 6 armor (3 icons). And they stay with any set.
Also, enchanting with Protection IV works fine - damage decreases noticeably with full enchanted set.

![2024-03-12_18 29 38](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/2423ef67-3f7e-41b6-9fe5-f7cf43875973) ![2024-03-12_18 30 04](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/0c59c47e-0ef0-4c19-95bb-cec79f4402b7)
![2024-03-12_19 43 58](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/27539d83-806e-488a-b9e3-d5d31f538da5)

On this dog I put Netherite chest first - 8 armor (4 icons). They stay if take off armor
![2024-03-12_21 33 43](https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/b9547b85-76ea-4b57-b052-fd362ec835d2)

**Comment by DashieDev** [comment]
Currently the Armor menu in the current release is buggy in the Fabric Port as i forgot some stuff.. I fixed it and will release it in DTN1.18.9

**Comment by DashieDev** [comment]
Fixed in DTN1.20.1-1.18.9 for Fabric

**Comment by Kavaltheone** [comment]
I'm sorry, but on version 1.18.10 (DoggyTalentsNext[Fabric]-1.20.1-1.18.10) still don't work
Made new dog and recorded result


https://github.com/DashieDev/DoggyTalentsNext/assets/12968480/6b63eb69-d1dc-4aa0-8dea-0b891e58bdd0
